<?php

// Run if we need to set up ACF fields/posts
exit;

/*
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6694e6d83c09d',
	'title' => 'Slider options',
	'fields' => array(
		array(
			'key' => 'field_6694e6d84465d',
			'label' => 'Enable pagination',
			'name' => 'enable_pagination',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_6694e7224465e',
			'label' => 'Enable nav',
			'name' => 'enable_nav',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_6694e7234465f',
			'label' => 'Enable scrollbar',
			'name' => 'enable_scrollbar',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'slider',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_669537062f04c',
	'title' => 'Slider select',
	'fields' => array(
		array(
			'key' => 'field_6695370648c0e',
			'label' => 'slider-selector',
			'name' => 'slider-selector',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'slider',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'contradata/slider-block',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6694262633ef0',
	'title' => 'Slides',
	'fields' => array(
		array(
			'key' => 'field_669428ce44068',
			'label' => 'Slide',
			'name' => 'slide',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6694261e9adf2',
					'label' => 'Slide headline',
					'name' => 'slide_headline',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_669428ce44068',
				),
				array(
					'key' => 'field_66942702b2c0d',
					'label' => 'Slide text',
					'name' => 'slide_text',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
					'parent_repeater' => 'field_669428ce44068',
				),
				array(
					'key' => 'field_6694271bb2c0e',
					'label' => 'Slide background image',
					'name' => 'slide_background_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_669428ce44068',
				),
				array(
					'key' => 'field_66942a0d71753',
					'label' => 'Slide image content',
					'name' => 'slide_image_content',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_669428ce44068',
				),
				array(
					'key' => 'field_66942a2571754',
					'label' => 'Slide link',
					'name' => 'slide_link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'parent_repeater' => 'field_669428ce44068',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'slider',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );
} );

add_action( 'init', function() {
	register_post_type( 'slider', array(
	'labels' => array(
		'name' => 'Sliders',
		'singular_name' => 'Slider',
		'menu_name' => 'Sliders',
		'all_items' => 'All Sliders',
		'edit_item' => 'Edit Slider',
		'view_item' => 'View Slider',
		'view_items' => 'View Sliders',
		'add_new_item' => 'Add New Slider',
		'add_new' => 'Add New Slider',
		'new_item' => 'New Slider',
		'parent_item_colon' => 'Parent Slider:',
		'search_items' => 'Search Sliders',
		'not_found' => 'No sliders found',
		'not_found_in_trash' => 'No sliders found in Trash',
		'archives' => 'Slider Archives',
		'attributes' => 'Slider Attributes',
		'insert_into_item' => 'Insert into slider',
		'uploaded_to_this_item' => 'Uploaded to this slider',
		'filter_items_list' => 'Filter sliders list',
		'filter_by_date' => 'Filter sliders by date',
		'items_list_navigation' => 'Sliders list navigation',
		'items_list' => 'Sliders list',
		'item_published' => 'Slider published.',
		'item_published_privately' => 'Slider published privately.',
		'item_reverted_to_draft' => 'Slider reverted to draft.',
		'item_scheduled' => 'Slider scheduled.',
		'item_updated' => 'Slider updated.',
		'item_link' => 'Slider Link',
		'item_link_description' => 'A link to a slider.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-cover-image',
	'supports' => array(
		0 => 'title',
	),
	'delete_with_user' => false,
) );
} );


